### ISSUE TITLE
v2 - SP metadata - NameID should be configurable

### ISSUE THREAD

**Issue by fhanik** [spring-projects/spring-security-saml#266]
Support a list of NameID URNs through configuration

Acceptance:

```
spring:
  security:
    saml2:
      service-provider:
        name-ids:
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
          - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          - urn:oasis:names:tc:SAML:2.0:nameid-format:transient
```

When viewing metadata, these three NameIDs should be present, no more, no less
