### ISSUE TITLE
v2 - global logout

### ISSUE THREAD

**Issue by dutrieux** [spring-projects/spring-security-saml#364]
I try to find how I can't have the global logout (not juste application but idp too) and I don't find a solution with the v2.
With v1 there is SAMLLogoutProcessingFilter class for that, but not exist on v2.

Could you please explain me how I can do that.

Best regards

**Comment by fhanik** [comment]
On an SP

`/saml/sp/logout`

On an IDP

`/saml/idp/logout`

Login is built in by default. You can enable/disable it

```
      service-provider:
        entity-id: spring.security.saml.sp.id
        alias: boot-sample-sp
        single-logout-enabled: true

      identity-provider:
        entity-id: spring.security.saml.idp.id
        alias: boot-sample-idp
        single-logout-enabled: false
```
